services:
    database:
        container_name: database_P13
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: greengoodies
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "4306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
    php:
        container_name: php_P13
        build:
            context: ./
        ports:
            - 8080:80
        volumes:
            - ./default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
            - ./:/var/www
        depends_on:
            - database
    phpma:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_P13
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: secret
            UPLOAD_LIMIT: 20M
        ports:
            - 8899:80
volumes:
    mysql_data:
